# Generated by Django 3.2.10 on 2022-07-08 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20220708_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerurls',
            name='owner',
        ),
        migrations.AddField(
            model_name='ownerurls',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
