# Generated by Django 3.2.10 on 2022-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220708_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerurls',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
